### PR TITLE
refactor(src): refactor index.js

### LINKED ISSUE #6: Refactor the email validator
The email validator seems too liberal at times, and the code can definitely be made more concise using regexes.
Eg:
We could replace Lines 11-25 with regexes.

Also, the checks seem unnecessarily verbose, 
Eg:
L23 can be simplified to : `if (atPos <1 || atPos === value.length)`

Maybe a single regex like this?

```
^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$
```

or if we do not strip trailing or leading spaces:

```
\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b
```

or for better readability, with grouping to extract username, domain etc: (I am not sure if the third part is legal, so let me know)

```
\b([\w.%+-]+)@([\w.-]+)\.(\w{2,4})\b
```

Looking closer at all the checks, I believe this regex would capture all the tests into one(including checking for dot after dot and dash after dot):

```
\b([\w.%+-]+)@([\w-]+)(?:\.(\w{2,4})){1,3}\b
```

tested this with:

```
foo@demo.net
bar.ba@test.co.uk
bar at@test..com
at@test.-abc.com
```

And only the first two are valid, which is what the validator would have displayed as well.
With this one, we can extract the username like so,
`matches[0]`
domain-name like so:
`matches[1]`
domain-extension like so:
`matches[2]`

I can make a PR if you guys think this is worth the change :)
EDIT: If anyone wants to play with the regexes:
http://www.regexr.com/ is a good place.
@6a68 
@pdehaan

### PR DESCRIPTION
**Pull request by TDA**
refactored index to use regexs instead
Fixes #6 
@pdehaan 
@6a68

### CODE REVIEW

**Comment by jrgm** [comment]
Umm, er. Please see https://github.com/mozilla/fxa-auth-server/commit/7ef3dcbac3514d095561b069c1e1955ee5eb837a where an explicit choice was to use that code. The point of this repository is to make that code reusable, not to rewrite decisions that were previously settled.

**Comment by TDA** [comment]
Okies :( @jrgm

**Comment by TDA** [comment]
@jrgm Would it be better if i wrote tests for this, and made sure they all pass?

**Comment by pdehaan** [comment]
@TDA: I don't think it'd give you a better chance of landing this code (per comment above and reasons in https://github.com/mozilla/fxa-auth-server/pull/573), but you're welcome to write/copy tests for this repo (see #1).

**Comment by jaredhirsch** [comment]
@TDA To quote the Bard,

> There are more things in heaven and earth, Horatio,
> Than are dreamt of in your philosophy.

[Related.](http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454)

To be a bit more direct: this repo exists so that I can reuse the FxA email validation logic in an unrelated project (https://github.com/mozilla/idea-town-splash), rather than copy-pasting it.

See [MDN](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation#Semantic_input_types) and [the whatwg spec](https://html.spec.whatwg.org/multipage/forms.html#e-mail-state-%28type=email%29) for the goriest of gory details.

**Comment by TDA** [comment]
@6a68 I dont see how "related" is related. We are parsing a string here, not html. html is not regular, email strings definitely are, seeing as every BNF has an equivalent representation in RegExp. We were not handling issues like `multiple` or any other attr in the previous code, and I am pretty positive that this code does _exactly_ what was being done before, only in like 1/5th of the LoC.
I can understand if the code is not meant to be changed, but dont we refactor all the time? why not here?

**Comment by pdehaan** [comment]
@TDA Let's take this offline and me+you can talk about it on IRC. :beers: 

---

> _"Some people, when confronted with a problem, think, “I know, I’ll use regular expressions.” Now they have two problems."_
> &mdash; Jamie Zawinksi

**Pull request closed without merging**
